services:
  # PHP + Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pickleplay-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - pickleplay
    depends_on:
      - redis
    environment:
      - DB_CONNECTION=pgsql
      - DB_URL=${DB_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: pickleplay-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - pickleplay
    depends_on:
      - app

  # Redis (for caching/queues)
  redis:
    image: redis:alpine
    container_name: pickleplay-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pickleplay
    volumes:
      - redis-data:/data

networks:
  pickleplay:
    driver: bridge

volumes:
  redis-data:
    driver: local
